<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenDialog_EditButton_EGI</name>
   <tag></tag>
   <elementGuidId>e7c20506-6663-4a7a-9c40-e55923c6f72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[1]/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.MuiTypography-root.MuiTypography-subtitle2.css-1dqd5sv-MuiTypography-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Sửa&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>bbceb8fa-fa9c-42f8-af2c-2d2fb374d057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subtitle2 css-1dqd5sv-MuiTypography-root</value>
      <webElementGuid>fd75990f-b468-4895-bed8-e65da301cf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sửa</value>
      <webElementGuid>b00c4bf4-9341-47c5-800c-a97f44264f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-menu&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiPopover-paper MuiMenu-paper MuiMenu-paper css-1jyi7yi-MuiPaper-root-MuiPopover-paper-MuiMenu-paper&quot;]/ul[@class=&quot;MuiList-root MuiList-padding MuiMenu-list css-1bemhkb-MuiList-root-MuiMenu-list&quot;]/li[@class=&quot;MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-hfe7fj-MuiButtonBase-root-MuiMenuItem-root&quot;]/div[@class=&quot;MuiBox-root css-dxieyw&quot;]/h6[@class=&quot;MuiTypography-root MuiTypography-subtitle2 css-1dqd5sv-MuiTypography-root&quot;]</value>
      <webElementGuid>c162ddc7-8101-4657-ac6b-007ba66ff34c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simple-menu']/div[3]/ul/li/div/h6</value>
      <webElementGuid>2da1acba-e2e5-4f94-b353-0c08789a7f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::h6[1]</value>
      <webElementGuid>45f29ee7-f8f0-41ee-83eb-afb0584b8e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/preceding::h6[1]</value>
      <webElementGuid>259da76f-9ed2-4063-bac0-8897cdef99b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khóa nhóm'])[1]/preceding::h6[2]</value>
      <webElementGuid>61f079d3-d5f8-48c5-9fcf-94d425092b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sửa']/parent::*</value>
      <webElementGuid>e3b39a2c-6e43-41fc-9866-5360cfff64c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/h6</value>
      <webElementGuid>b348b7d8-140d-4356-a2fc-9fcdef0dad38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Sửa' or . = 'Sửa')]</value>
      <webElementGuid>b0ebf6aa-cff4-4822-b855-a86af3686b9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
